<?php


namespace Pinepain\SimpleConfig\Loaders;

class FileCacheLoader implements LoaderInterface
{
    /**
     * @var LoaderInterface
     */
    private $loader;

    /**
     * @var string
     */
    private $cache_file;

    public function __construct(LoaderInterface $loader, $cache_file)
    {
        $this->loader     = $loader;
        $this->cache_file = $cache_file;
    }

    /**
     * {@inheritdoc}
     */
    public function load()
    {
        if (!file_exists($this->cache_file)) {
            $items = $this->loader->load();

            $this->generateCache($this->cache_file, $items);

            return $items;
        }

        return require $this->cache_file;
    }

    /**
     * Store config items in file that can be simply `required` later
     *
     * @param string $cache_file
     * @param array  $items
     */
    public function generateCache($cache_file, $items)
    {
        $out = var_export($items, true);

        file_put_contents($cache_file,
            '<?php' . PHP_EOL . PHP_EOL
            . '// THIS IS AUTOGENERATED FILE! DO NOT EDIT IT!' . PHP_EOL . PHP_EOL
            . 'return ' . $out . ';' . PHP_EOL
        );
    }
}